# 导航菜单配置
menu:
  # 首页
  - id: home
    link: /
  # 爱好
  - id: hobby
    link: /hobby
  # 关于
  - id: about
    link: /about

# 配置 CDN 加速脚本加载
cdn:
  jquery: https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js
  bootstrap: 'https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js'
